
#ifndef __KEY_CONST_H__
#define __KEY_CONST_H__

#define AMLKEY_NOP    0

#define AMLKEY_NUM_PLUS10    1

#define AMLKEY_NUM_0    2

#define AMLKEY_NUM_1    3

#define AMLKEY_NUM_2    4

#define AMLKEY_NUM_3    5

#define AMLKEY_NUM_4    6

#define AMLKEY_NUM_5    7

#define AMLKEY_NUM_6    8

#define AMLKEY_NUM_7    9

#define AMLKEY_NUM_8    10

#define AMLKEY_NUM_9    11

#define AMLKEY_UP    12

#define AMLKEY_DOWN    13

#define AMLKEY_LEFT    14

#define AMLKEY_RIGHT    15

#define AMLKEY_ENTER    16

#define AMLKEY_EXIT    17

#define AMLKEY_PAGE_UP    18

#define AMLKEY_PAGE_DOWN    19

#define AMLKEY_POWER    20

#define AMLKEY_SLEEP    21

#define AMLKEY_HOME    22

#define AMLKEY_SETUP    23

#define AMLKEY_OSD    24

#define AMLKEY_MENU    25

#define AMLKEY_DISPLAY    26

#define AMLKEY_MARK    27

#define AMLKEY_CLEAR    28

#define AMLKEY_PLAY_PAUSE    29

#define AMLKEY_STOP    30

#define AMLKEY_PAUSE    31

#define AMLKEY_NEXT_CHAP    32

#define AMLKEY_PREVIOUS_CHAP    33

#define AMLKEY_FAST_FORWARD    34

#define AMLKEY_FAST_BACKWARD    35

#define AMLKEY_REPEAT    36

#define AMLKEY_PLAY_MODE    37

#define AMLKEY_SLIDE_SHOW    38

#define AMLKEY_MUTE    39

#define AMLKEY_VOL_MINUS    40

#define AMLKEY_VOL_PLUS    41

#define AMLKEY_ZOOM    42

#define AMLKEY_ROTATE    43

#define AMLKEY_MOUSE_L_DOWN    44

#define AMLKEY_MOUSE_L_UP    45

#define AMLKEY_MOUSE_R_DOWN    46

#define AMLKEY_MOUSE_R_UP    47

#define AMLKEY_MOUSE_M_DOWN    48

#define AMLKEY_MOUSE_M_UP    49

#define AMLKEY_MOUSE_ROLL_DOWN    50

#define AMLKEY_MOUSE_ROLL_UP    51

#define AMLKEY_MOUSE_MOVE    52

#define AMLKEY_LONG_EXIT    53

#define AMLKEY_LONG_RIGHT    54

#define AMLKEY_LONG_LEFT    55

#define AMLKEY_LONG_DOWN    56

#define AMLKEY_LONG_UP    57

#define AMLKEY_LONG_ENTER    58

#define AMLKEY_LONG_MENU    59

#define AMLKEY_OPEN_CLOSE    60

#define AMLKEY_NTSC_PAL    61

#define AMLKEY_PROGRESSIVE    62

#define AMLKEY_TITLE_CALL    63

#define AMLKEY_AUDIO    64

#define AMLKEY_SUBPICTURE    65

#define AMLKEY_ANGLE    66

#define AMLKEY_AB_PLAY    67

#define AMLKEY_RECODE    68

#define AMLKEY_SHORTCUT    69

#define AMLKEY_ORIGINAL    70

#define AMLKEY_BOOKING    71

#define AMLKEY_ORDER_SYSTEM    72

#define AMLKEY_SOUND_CTRL    73

#define AMLKEY_FUNCTION    74

#define AMLKEY_SCHEDULE    75

#define AMLKEY_FAVOR    76

#define AMLKEY_RELATION    77

#define AMLKEY_FIRST    78

#define AMLKEY_DELETE    79

#define AMLKEY_SLIDE_RELEASE    80

#define AMLKEY_SLIDE_TOUCH    81

#define AMLKEY_SLIDE_LEFT    82

#define AMLKEY_SLIDE_RIGHT    83

#define AMLKEY_SLIDE_UP    84

#define AMLKEY_SLIDE_DOWN    85

#define AMLKEY_SLIDE_CLOCKWISE    86

#define AMLKEY_SLIDE_ANTI_CLOCKWISE    87

#define AMLKEY_SLIDE_UP_LEFT    88

#define AMLKEY_SLIDE_UP_RIGHT    89

#define AMLKEY_SLIDE_DOWN_LEFT    90

#define AMLKEY_SLIDE_DOWN_RIGHT    91

#define AMLKEY_SLIDE_NULL    92

#define AMLKEY_MENU_CALL    93

#define AMLKEY_AMLKEYBOARD_A    94

#define AMLKEY_AMLKEYBOARD_B    95

#define AMLKEY_AMLKEYBOARD_C    96

#define AMLKEY_AMLKEYBOARD_D    97

#define AMLKEY_AMLKEYBOARD_E    98

#define AMLKEY_AMLKEYBOARD_F    99

#define AMLKEY_AMLKEYBOARD_G    100

#define AMLKEY_AMLKEYBOARD_H    101

#define AMLKEY_AMLKEYBOARD_I    102

#define AMLKEY_AMLKEYBOARD_J    103

#define AMLKEY_AMLKEYBOARD_K    104

#define AMLKEY_AMLKEYBOARD_L    105

#define AMLKEY_AMLKEYBOARD_M    106

#define AMLKEY_AMLKEYBOARD_N    107

#define AMLKEY_AMLKEYBOARD_O    108

#define AMLKEY_AMLKEYBOARD_P    109

#define AMLKEY_AMLKEYBOARD_Q    110

#define AMLKEY_AMLKEYBOARD_R    111

#define AMLKEY_AMLKEYBOARD_S    112

#define AMLKEY_AMLKEYBOARD_T    113

#define AMLKEY_AMLKEYBOARD_U    114

#define AMLKEY_AMLKEYBOARD_V    115

#define AMLKEY_AMLKEYBOARD_W    116

#define AMLKEY_AMLKEYBOARD_X    117

#define AMLKEY_AMLKEYBOARD_Y    118

#define AMLKEY_AMLKEYBOARD_Z    119

#define AMLKEY_AMLKEYBOARD_0    120

#define AMLKEY_AMLKEYBOARD_1    121

#define AMLKEY_AMLKEYBOARD_2    122

#define AMLKEY_AMLKEYBOARD_3    123

#define AMLKEY_AMLKEYBOARD_4    124

#define AMLKEY_AMLKEYBOARD_5    125

#define AMLKEY_AMLKEYBOARD_6    126

#define AMLKEY_AMLKEYBOARD_7    127

#define AMLKEY_AMLKEYBOARD_8    128

#define AMLKEY_AMLKEYBOARD_9    129

#define AMLKEY_AMLKEYBOARD_ENTER    130

#define AMLKEY_AMLKEYBOARD_SPACE    131

#define AMLKEY_AMLKEYBOARD_BACKSPACE    132

#define AMLKEY_AMLKEYBOARD_ESC    133

#define AMLKEY_AMLKEYBOARD_CAESURA_SIGN    134

#define AMLKEY_AMLKEYBOARD_SUBTRACTION_SIGN    135

#define AMLKEY_AMLKEYBOARD_EQUALS_SIGN    136

#define AMLKEY_AMLKEYBOARD_LEFT_BRACKET    137

#define AMLKEY_AMLKEYBOARD_RIGHT_BRACKET    138

#define AMLKEY_AMLKEYBOARD_BACKSLASH    139

#define AMLKEY_AMLKEYBOARD_SEMICOLON    140

#define AMLKEY_AMLKEYBOARD_QUOTATION_MARK    141

#define AMLKEY_AMLKEYBOARD_COMMA    142

#define AMLKEY_AMLKEYBOARD_POINT    143

#define AMLKEY_AMLKEYBOARD_SLASH    144

#define AMLKEY_ALARM_SET    145

#define AMLKEY_ALARM_OFF    146

#define AMLKEY_IPOD_PLAY_PAUSE    147

#define AMLKEY_B_TIME_SET_MINUS    148

#define AMLKEY_B_TIME_SET_PLUS    149

#define AMLKEY_ALARM_B_ONOFF    150

#define AMLKEY_SNOOZE_BRIGHTNESS    151

#define AMLKEY_ALARM_A_ONOFF    152

#define AMLKEY_A_TIME_SET_MINUS    153

#define AMLKEY_A_TIME_SET_PLUS    154

#define AMLKEY_BACK    155

#define AMLKEY_RADIO_BAND    156

#define AMLKEY_OPTION    157

#define AMLKEY_LONG_B_TIME_SET_MINUS    158

#define AMLKEY_LONG_B_TIME_SET_PLUS    159

#define AMLKEY_LONG_A_TIME_SET_MINUS    160

#define AMLKEY_LONG_A_TIME_SET_PLUS    161

#define AMLKEY_LONG2_B_TIME_SET_MINUS    162

#define AMLKEY_LONG2_B_TIME_SET_PLUS    163

#define AMLKEY_LONG2_A_TIME_SET_MINUS    164

#define AMLKEY_LONG2_A_TIME_SET_PLUS    165

#define AMLKEY_LONG2_LEFT    166

#define AMLKEY_LONG2_RIGHT    167

#define AMLKEY_LONGRLS_LEFT    168

#define AMLKEY_LONGRLS_RIGHT    169

#define AMLKEY_LONGRLS_B_TIME_SET_MINUS    170

#define AMLKEY_LONGRLS_B_TIME_SET_PLUS    171

#define AMLKEY_LONGRLS_A_TIME_SET_MINUS    172

#define AMLKEY_LONGRLS_A_TIME_SET_PLUS    173

#define AMLKEY_LONG2RLS_LEFT    174

#define AMLKEY_LONG2RLS_RIGHT    175

#define AMLKEY_LONG2RLS_B_TIME_SET_MINUS    176

#define AMLKEY_LONG2RLS_B_TIME_SET_PLUS    177

#define AMLKEY_LONG2RLS_A_TIME_SET_MINUS    178

#define AMLKEY_LONG2RLS_A_TIME_SET_PLUS    179

/*
<<ConstantSetName>> AMLKEY
*/


/*
<<AfControlWizardVersion>> 0000021d
*/

/*<<Magic>> 0006c848
*/

#endif
