#ifndef TASK_PRIORITY_H
#define TASK_PRIORITY_H

#define TASK_PRIORITY_AUDIO_NEC_CONTROL 	27
#define TASK_PRIORITY_AUDIO_CEC_CONTROL 	26
#define TASK_PRIORITY_AUDIO_PROCESS 		25
#define TASK_PRIORITY_DBG					3
#define TASK_PRIORITY_VPP					23
#define TASK_PRIORITY_OSD					24
#define TASK_PRIORITY_LOG   				1
#define TASK_PRIORITY_SARADC				4
#define TASK_PRIORITY_INPUT					29
#define TASK_PRIORITY_CONSOLE 				2
#define TASK_PRIORITY_UART1					31
#define TASK_PRIORITY_UART_COMMUNICATION	30
#define TASK_PRIORITY_REMOTE				5
#define TASK_PRIORITY_USER					6
#define TASK_PRIORITY_AUTO_BACKLIGHT		7
#define TASK_PRIORITY_REMOTE_RCA			8
#define TASK_PRIORITY_CPU_IDLE				28
#define TASK_PRIORITY_BURN                  9
#define TASK_PRIORITY_OPC					21
#define TASK_PRIORITY_HDMIRX				22
#define TASK_PRIORITY_LOCAL_DIMING			20

#endif

